'use client'

import { useMemo, useState } from 'react'

type Language = 'hi' | 'en' | 'hinglish'
type Screen = 'check' | 'result' | 'pause' | 'sent'
type Verdict = 'likely_scam' | 'uncertain' | 'no_red_flags_found'
type Flag = { id?: string; label_en: string; label_hi: string; evidence: string }
type Confidence = 'low' | 'medium' | 'high'
type Analysis = { verdict: Verdict; risk_score: number; confidence?: Confidence; red_flags: Flag[]; explanation_en: string; explanation_hi: string; next_steps_en: string[]; next_steps_hi: string[]; disclaimer?: string; analysis_mode?: string }

const languages: { value: Language; label: string }[] = [{ value: 'hi', label: 'हिन्दी' }, { value: 'en', label: 'English' }, { value: 'hinglish', label: 'Hinglish' }]
const examples = [
  { label: 'Guaranteed returns VIP group', text: 'Join our VIP investment group today. Guaranteed 30% returns with no risk. Pay now to secure your seat.' },
  { label: 'Fake SEBI AnyDesk call', text: 'This is SEBI calling. Install AnyDesk immediately so we can verify your trading account and release your refund.' },
  { label: 'Hinglish paisa double group', text: 'Bhai paisa double scheme hai, bas aaj payment karo. VIP group mein add kar denge, jaldi karo.' },
]
const copy = {
  en: { hero: "Got an investment 'tip' on WhatsApp? Check before you pay.", input: 'Paste the message you received', placeholder: 'WhatsApp, SMS, email, or call transcript…', check: 'Check message', try: 'Try an example', trust: 'Server-side privacy masking: raw [UPI], [PHONE] and [ACCOUNT] details are removed before analysis. No raw PII is sent to or processed by third-party LLM APIs · Not investment advice · We never recommend stocks', stages: ['Hiding personal details…', 'Checking known scam patterns…', 'Getting an AI second opinion…'], cancel: 'Cancel', empty: 'Paste a message first so we can check it.', error: 'We could not reach the checker. Please try again, or check your connection.', result: 'Your result', message: 'Your message', why: 'Why we think so', explanation: 'Explanation', listen: 'Listen', stop: 'Stop listening', risk: 'Risk score', flags: 'Red flags found', next: 'What to do now', steps: 'Next steps', pause: 'Pause before you pay', pauseIntro: 'A quick cooling-off check. If any answer is Yes, stop.', yes: 'Yes', no: 'No', stopPay: 'Stop. Do not pay.', safe: 'No immediate payment red flags. Still take your time.', another: 'Check another message', share: 'Share this warning', call: 'Call 1930', cyber: 'Report at cybercrime.gov.in', sebi: 'Complain at SEBI SCORES', listeningUnsupported: 'Listening is not available in this browser.', questions: ['Did someone promise fixed returns?', 'Were you told to hurry?', 'Are you being asked to pay a personal account or install an app?'], verdicts: { likely_scam: 'Likely scam', uncertain: 'Uncertain', no_red_flags_found: 'No red flags found' }, sentMoney: 'I already sent money', sentTitle: 'If you already sent money', sentSteps: ['Call your bank or UPI app\'s helpline now.', 'Call 1930.', 'Report at cybercrime.gov.in.', 'Keep evidence: screenshots, the UPI ID or number you paid, transaction ID, date and time.', 'Do NOT pay anyone offering to "recover" your money.', 'Never share OTP or PIN.'], sentNote: 'Complaint against a SEBI-registered broker or listed company? Use scores.sebi.gov.in', sentFooter: 'Sachet is not a government service and cannot file complaints, freeze accounts or recover money.', sentBack: 'Back to Sachet' },
  hi: { hero: "WhatsApp पर निवेश की 'टिप' मिली? पैसे भेजने से पहले जाँचें।", input: 'आपको मिला संदेश यहाँ चिपकाएँ', placeholder: 'WhatsApp, SMS, ईमेल या कॉल का संदेश…', check: 'संदेश जाँचें', try: 'उदाहरण आज़माएँ', trust: 'सर्वर-साइड प्राइवेसी मास्किंग: कच्चे [UPI], [PHONE] और [ACCOUNT] विवरण जाँच से पहले हटा दिए जाते हैं। कच्ची PII किसी third-party LLM को नहीं भेजी या प्रोसेस की जाती · निवेश सलाह नहीं · हम स्टॉक की सलाह नहीं देते', stages: ['निजी जानकारी छिपाई जा रही है…', 'ज्ञात धोखाधड़ी पैटर्न जाँचे जा रहे हैं…', 'AI की दूसरी राय ली जा रही है…'], cancel: 'रद्द करें', empty: 'पहले कोई संदेश डालें।', error: 'चेकर तक पहुँच नहीं हो सकी। कनेक्शन जाँचकर फिर कोशिश करें।', result: 'आपका नतीजा', message: 'आपका संदेश', why: 'ऐसा क्यों लगा', explanation: 'समझिए', listen: 'सुनें', stop: 'सुनना रोकें', risk: 'जोखिम स्कोर', flags: 'खतरे के संकेत', next: 'अब क्या करें', steps: 'अगले कदम', pause: 'भुगतान से पहले रुकें', pauseIntro: 'एक छोटा विराम चेक। किसी का जवाब हाँ हो तो रुकें।', yes: 'हाँ', no: 'नहीं', stopPay: 'रुकें। भुगतान न करें।', safe: 'भुगतान से जुड़े तुरंत खतरे नहीं दिखे। फिर भी समय लें।', another: 'दूसरा संदेश जाँचें', share: 'यह चेतावनी साझा करें', call: '1930 पर कॉल करें', cyber: 'cybercrime.gov.in पर रिपोर्ट करें', sebi: 'SEBI SCORES पर शिकायत करें', listeningUnsupported: 'इस ब्राउज़र में सुनना उपलब्ध नहीं है।', questions: ['क्या किसी ने तय मुनाफे का वादा किया?', 'क्या आपको जल्दी करने को कहा गया?', 'क्या निजी खाते में पैसे देने या ऐप इंस्टॉल करने को कहा गया?'], verdicts: { likely_scam: 'धोखाधड़ी की संभावना', uncertain: 'अनिश्चित', no_red_flags_found: 'कोई खतरे का संकेत नहीं' }, sentMoney: 'मैंने पैसे भेज दिए हैं', sentTitle: 'अगर आपने पैसे भेज दिए हैं', sentSteps: ['अभी अपने बैंक या UPI ऐप की हेल्पलाइन पर कॉल करें।', '1930 पर कॉल करें।', 'cybercrime.gov.in पर रिपोर्ट करें।', 'सबूत रखें: स्क्रीनशॉट, जिस UPI ID या नंबर पर पैसे भेजे, ट्रांज़ैक्शन ID, तारीख और समय।', 'पैसे "वापस दिलाने" का दावा करने वाले किसी व्यक्ति को पैसे न दें।', 'OTP या PIN कभी साझा न करें।'], sentNote: 'SEBI-रजिस्टर्ड ब्रोकर या सूचीबद्ध कंपनी के खिलाफ शिकायत? scores.sebi.gov.in का उपयोग करें।', sentFooter: 'सचेत सरकारी सेवा नहीं है और शिकायत दर्ज, खाते फ्रीज़ या पैसे वापस नहीं कर सकता।', sentBack: "सचेत पर वापस जाएँ" },
  hinglish: { hero: "WhatsApp par investment ki 'tip' mili? Paise bhejne se pehle check karo.", input: 'Jo message mila, yahan paste karo', placeholder: 'WhatsApp, SMS, email ya call transcript…', check: 'Message check karo', try: 'Example try karo', trust: 'Server-side privacy masking: raw [UPI], [PHONE] aur [ACCOUNT] details analysis se pehle remove ho jaati hain. Raw PII kisi third-party LLM ko send ya process nahi hoti · Investment advice nahi · Stocks recommend nahi karte', stages: ['Personal details hide ho rahe hain…', 'Known scam patterns check ho rahe hain…', 'AI second opinion mil rahi hai…'], cancel: 'Cancel', empty: 'Pehle message paste karo.', error: 'Checker tak pahunch nahi paaye. Connection check karke phir try karo.', result: 'Aapka result', message: 'Aapka message', why: 'Aisa kyun laga', explanation: 'Explanation', listen: 'Suno', stop: 'Sunna roko', risk: 'Risk score', flags: 'Red flags', next: 'Ab kya karein', steps: 'Next steps', pause: 'Pay karne se pehle ruko', pauseIntro: 'Quick cooling-off check. Koi bhi Yes ho, ruk jao.', yes: 'Yes', no: 'No', stopPay: 'Stop. Pay mat karo.', safe: 'Koi immediate payment red flag nahi mila. Phir bhi time lo.', another: 'Doosra message check karo', share: 'Warning share karo', call: '1930 par call karo', cyber: 'cybercrime.gov.in par report karo', sebi: 'SEBI SCORES par complain karo', listeningUnsupported: 'Is browser mein listening available nahi hai.', questions: ['Kya kisi ne fixed returns promise kiye?', 'Kya tumhe hurry karne ko bola?', 'Kya personal account mein pay ya app install karne ko kaha?'], verdicts: { likely_scam: 'Scam lag raha hai', uncertain: 'Uncertain', no_red_flags_found: 'Koi red flag nahi mila' }, sentMoney: 'Maine paise bhej diye hain', sentTitle: 'Agar aapne paise bhej diye hain', sentSteps: ['Abhi apne bank ya UPI app ki helpline par call karein.', '1930 par call karein.', 'cybercrime.gov.in par report karein.', 'Evidence sambhal kar rakhein: screenshots, jis UPI ID ya number par pay kiya, transaction ID, date aur time.', 'Paise "recover" karne ka offer dene wale ko pay NA karein.', 'OTP ya PIN kabhi share na karein.'], sentNote: 'SEBI-registered broker ya listed company ke khilaaf complaint? scores.sebi.gov.in use karein.', sentFooter: 'Sachet government service nahi hai aur complaints file, accounts freeze ya paise recover nahi kar sakta.', sentBack: "Sachet par wapas jaayein" },
}

function highlight(text: string, flags: Flag[]) { const matches = flags.map((f) => f.evidence).filter(Boolean).sort((a, b) => b.length - a.length); if (!matches.length) return text; const re = new RegExp(`(${matches.map((x) => x.replace(/[.*+?^${}()|[\\]\\\\]/g, '\\$&')).join('|')})`, 'gi'); return text.split(re).map((part, i) => matches.some((m) => m.toLowerCase() === part.toLowerCase()) ? <mark key={i}>{part}</mark> : part) }
function friendlyEvidence(text: string) { const labels: Record<string, string> = { '[UPI]': 'UPI ID hidden', '[PHONE]': 'Phone number hidden', '[ACCOUNT]': 'Account number hidden' }; return text.split(/(\\[UPI\\]|\\[PHONE\\]|\\[ACCOUNT\\])/g).map((part, i) => labels[part] ? <span className="privacy-pill" key={i}>{labels[part]}</span> : part) }
function normalizeDraftText(text: string) { return text.replace(/\\\\n/g, '\n').replace(/\\\\r/g, '\r') }

type CrimeReportData = { complainantName: string; incidentDateTime: string; amount: string; paymentMode: string; transactionId: string; suspectDetails: string; source: string; evidenceTextSnippet: string }

function generateNationalCybercrimeDraft(data: CrimeReportData, lang: Language) {
  const value = (input: string) => input.trim() || (lang === 'hi' ? 'उपलब्ध नहीं' : 'Not provided')
  const reportDate = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })
  if (lang === 'hi') {
    return `====================================================================
साइबर अपराध शिकायत रिपोर्ट (Sachet से तैयार)
====================================================================
प्रति,
साइबर क्राइम सेल / राष्ट्रीय साइबर अपराध रिपोर्टिंग पोर्टल (1930)

विषय: वित्तीय साइबर धोखाधड़ी / अनधिकृत धन निकासी की तत्काल शिकायत

[1] लेन-देन का विवरण:
--------------------------------------------------------------------
- घटना की तारीख और समय: ${value(data.incidentDateTime)} IST
- राशि: ${value(data.amount)}
- भुगतान का माध्यम: ${value(data.paymentMode)}
- ट्रांज़ैक्शन ID / URN: ${value(data.transactionId)}
- संदिग्ध UPI ID / खाता / वॉलेट: ${value(data.suspectDetails)}
- घटना की शुरुआत: ${value(data.source)}

[2] डिजिटल सबूत और घटना का विवरण:
--------------------------------------------------------------------
Sachet ने इस संदेश में संभावित धोखाधड़ी के पैटर्न पाए:
“${value(data.evidenceTextSnippet)}”

[3] अनुरोध:
--------------------------------------------------------------------
कृपया इस शिकायत को साइबर अपराध प्रक्रिया के अनुसार दर्ज करें और संबंधित बैंकिंग माध्यम पर आवश्यक कार्रवाई करें।

रिपोर्ट तैयार होने की तारीख: ${reportDate} IST
यह मसौदा Sachet ने आपके दिए विवरण के आधार पर बनाया है।
====================================================================`
  }
  return `====================================================================
EVIDENTIARY COMPLAINT REPORT (GENERATED VIA PROJECT SACHET PROTOCOL)
====================================================================
To,
The Cyber Crime Cell / National Cyber Crime Reporting Portal (1930)

SUBJECT: Urgent Report of Financial Cyber Fraud / Unauthorized Fund Outflow

[1] TRANSACTION DETAILS:
--------------------------------------------------------------------
- Incident date and time: ${value(data.incidentDateTime)} IST
- Amount: ${value(data.amount)}
- Mode of payment: ${value(data.paymentMode)}
- Transaction reference ID / URN: ${value(data.transactionId)}
- Suspect identifier (UPI ID / account / phone): ${value(data.suspectDetails)}
- Where it started: ${value(data.source)}

[2] EVIDENCE AND NARRATIVE:
--------------------------------------------------------------------
Sachet identified potential scam patterns in the submitted message:
“${value(data.evidenceTextSnippet)}”

[3] ACTION REQUESTED:
--------------------------------------------------------------------
Please register this report under the applicable cybercrime process and take appropriate action with the beneficiary bank or payment rail.

Report date: ${reportDate} IST
Generated via Sachet Public Infrastructure
====================================================================`
}

function complaintLabels(lang: Language) {
  if (lang === 'hi') return { title: 'शिकायत तैयार करें', date: 'तारीख और समय', amount: 'राशि', paid: 'आपने कैसे भुगतान किया', recipient: 'प्राप्तकर्ता का UPI ID, खाता नंबर या फ़ोन नंबर', started: 'यह कहाँ से शुरू हुआ', transaction: 'ट्रांज़ैक्शन ID', happened: 'अपने शब्दों में क्या हुआ', generate: 'ड्राफ्ट बनाएँ', copy: 'कॉपी करें', share: 'साझा करें', note: 'दाखिल करने से पहले हर विवर��� जाँचें। यह ड्राफ्ट ��धिकारिक शिकायत नहीं है।', options: ['UPI', 'बैंक ट्रांसफ़र', 'अन्य'], origins: ['WhatsApp', 'Telegram', 'कॉल', 'अन्य'] }
  if (lang === 'hinglish') return { title: 'Complaint tayyar karein', date: 'Date aur time', amount: 'Amount', paid: 'Aapne kaise pay kiya', recipient: 'Recipient ka UPI ID, account number ya phone number', started: 'Yeh kahan se shuru hua', transaction: 'Transaction ID', happened: 'Apne words mein kya hua', generate: 'Draft generate karein', copy: 'Copy karein', share: 'Share karein', note: 'File karne se pehle har detail check karein. Yeh draft official complaint nahi hai.', options: ['UPI', 'Bank transfer', 'Other'], origins: ['WhatsApp', 'Telegram', 'Call', 'Other'] }
  return { title: 'Prepare your complaint', date: 'Date and time', amount: 'Amount', paid: 'How you paid', recipient: "Recipient's UPI ID, account number or phone number", started: 'Where it started', transaction: 'Transaction ID', happened: 'What happened, in your own words', generate: 'Generate draft', copy: 'Copy', share: 'Share', note: 'Check every detail before you file. This draft is not an official complaint.', options: ['UPI', 'Bank transfer', 'Other'], origins: ['WhatsApp', 'Telegram', 'Call', 'Other'] }
}

export default function Home() {
  const [lang, setLang] = useState<Language>(() => typeof navigator !== 'undefined' && navigator.language.toLowerCase().startsWith('hi') ? 'hi' : 'en')
  const [screen, setScreen] = useState<Screen>('check'); const [text, setText] = useState(''); const [analysis, setAnalysis] = useState<Analysis | null>(null); const [loading, setLoading] = useState(false); const [stage, setStage] = useState(0); const [error, setError] = useState(''); const [answers, setAnswers] = useState<boolean[]>([false, false, false]); const [speaking, setSpeaking] = useState(false)
  const [complaint, setComplaint] = useState({ date: '', amount: '', paid: 'UPI', recipient: '', started: 'WhatsApp', transaction: '', happened: '' }); const [draft, setDraft] = useState(''); const [listening, setListening] = useState(false)
  const t = copy[lang]; const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'https://sachet-rmgt.onrender.com'; const verdict = analysis ? t.verdicts[analysis.verdict] : ''
  const confidenceLabel = analysis?.confidence ? (lang === 'hi' ? ({ low: 'कम भरोसा', medium: 'मध्यम भरोसा', high: 'उच्च भरोसा' } as const)[analysis.confidence] : `${analysis.confidence[0].toUpperCase()}${analysis.confidence.slice(1)} confidence`) : ''
  const uniqueFlags = analysis?.red_flags?.filter((flag, index, flags) => flags.findIndex((candidate) => candidate.label_en === flag.label_en || candidate.evidence === flag.evidence) === index) || []
  async function checkMessage() { if (!text.trim()) { setError(t.empty); return } setLoading(true); setError(''); setStage(0); const timer = window.setInterval(() => setStage((s) => Math.min(2, s + 1)), 5000); const slowNotice = window.setTimeout(() => setError('Waking up the server and checking with AI, this can take up to 30 seconds.'), 6000); const abort = new AbortController(); const timeout = window.setTimeout(() => abort.abort(), 35000); try { const res = await fetch(`${apiUrl.replace(/\/$/, '')}/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text: text.trim(), lang }), signal: abort.signal }); if (!res.ok) throw new Error(); const data = await res.json() as Analysis; setAnalysis(data); setScreen('result') } catch { setError(t.error) } finally { clearInterval(timer); clearTimeout(slowNotice); clearTimeout(timeout); setLoading(false) } }
  function voice() { const Recognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition; if (!Recognition) { setError(t.listeningUnsupported); return } if (listening) return; const r = new Recognition(); r.lang = lang === 'hi' ? 'hi-IN' : 'en-IN'; r.onstart = () => { setListening(true); setError('') }; r.onresult = (e: any) => setText((v) => `${v}${v ? ' ' : ''}${e.results[0][0].transcript}`); r.onend = () => setListening(false); r.onerror = () => { setListening(false); setError(t.listeningUnsupported) }; r.start() }
  function listen() { if (!analysis || !('speechSynthesis' in window)) return; if (speaking) { speechSynthesis.cancel(); setSpeaking(false); return } const u = new SpeechSynthesisUtterance(lang === 'hi' ? analysis.explanation_hi : analysis.explanation_en); u.lang = lang === 'hi' ? 'hi-IN' : 'en-IN'; u.onend = () => setSpeaking(false); speechSynthesis.speak(u); setSpeaking(true) }
  const complaintText = complaintLabels(lang)
  function updateComplaint(field: keyof typeof complaint, value: string) { setComplaint((current) => ({ ...current, [field]: value })) }
  function generateDraft() {
    const details = complaint.happened || 'Not provided'
    const generated = generateNationalCybercrimeDraft({ complainantName: '', incidentDateTime: complaint.date, amount: complaint.amount, paymentMode: complaint.paid, transactionId: complaint.transaction, suspectDetails: complaint.recipient, source: complaint.started, evidenceTextSnippet: details }, lang)
    setDraft(normalizeDraftText(generated))
  }
  async function copyDraft() { if (!draft) return; await navigator.clipboard?.writeText(draft) }
  async function shareDraft() { if (!draft) return; if (navigator.share) await navigator.share({ text: draft }); else await copyDraft() }
  const reset = () => { setAnalysis(null); setText(''); setError(''); setDraft(''); setScreen('check') }
  return <main className="app-shell"><header className="topbar"><div className="brand"><span className="brand-mark">S</span><span>Sachet <span className="brand-native">सचेत</span></span></div><nav className="language-toggle" aria-label="Language">{languages.map((x) => <button key={x.value} onClick={() => setLang(x.value)} aria-pressed={lang === x.value} className={lang === x.value ? 'language-active' : ''}>{x.label}</button>)}</nav></header>
    {screen === 'check' && <section className="hero-section"><div className="hero-copy"><p className="eyebrow">SCAM-PATTERN CHECKER</p><h1>{t.hero}</h1><div className="examples"><span>{t.try}</span>{examples.map((x) => <button key={x.label} onClick={() => setText(x.text)}>{x.label}</button>)}</div></div><div className="checker-card"><label htmlFor="message" className="field-label">{t.input}</label><div className="textarea-wrap"><textarea id="message" value={text} onChange={(e) => { setText(e.target.value); setError('') }} placeholder={t.placeholder} rows={7} /><button className={`mic-button${listening ? ' mic-active' : ''}`} onClick={voice} aria-label={listening ? 'Listening' : 'Voice input'} aria-pressed={listening}><span className="mic-dot" aria-hidden="true">●</span>{listening && <span className="mic-status">Listening…</span>}</button></div>{error && <p className="error-text" role="alert">{error}</p>}<button className="primary-button" onClick={checkMessage} disabled={loading}>{loading ? <><span className="spinner" />{t.stages[stage]}</> : t.check}{loading && <small>{25 - stage * 5}s</small>}</button>{loading && <button className="cancel-button" onClick={() => window.location.reload()}>{t.cancel}</button>}<p className="trust-strip">{t.trust}</p></div><div className="home-actions"><button className="pause-link" onClick={() => setScreen('pause')}>◷ {t.pause}</button><button className="recovery-link" onClick={() => setScreen('sent')}>{t.sentMoney}</button></div></section>}
    {screen === 'result' && analysis && <section className="content-section"><div className="result-top"><div><p className="eyebrow">{t.result}</p><div className="verdict-heading"><h1>{verdict}</h1>{analysis.analysis_mode === 'rules_only' ? <span className="mode-badge limited">Offline check — AI unavailable</span> : analysis.analysis_mode === 'rules+llm' ? <span className="mode-badge assisted">AI-assisted check</span> : null}</div>{analysis.analysis_mode === 'rules_only' && <p className="mode-note">Showing known-pattern checks only.</p>}</div><button className="listen-button" onClick={listen}>{speaking ? t.stop : t.listen}</button></div><div className={`verdict-card verdict-${analysis.verdict}`}><span className="verdict-icon">{analysis.verdict === 'likely_scam' ? '!' : analysis.verdict === 'uncertain' ? '?' : '✓'}</span><strong>{verdict}</strong><span>{confidenceLabel}</span></div><div className="risk-block"><div className="row-between"><h2>{t.risk}</h2><strong>{analysis.risk_score}/100</strong></div><div className="risk-track"><div className={`risk-fill risk-${analysis.verdict}`} style={{ width: `${Math.max(0, Math.min(100, analysis.risk_score))}%` }} /></div></div><article className="message-box"><h2>{t.message}</h2><p>{highlight(text, analysis.red_flags || [])}</p></article>{uniqueFlags.length > 0 && <section><h2>{t.why}</h2><div className="flag-list">{uniqueFlags.map((f, i) => <article className="flag-item" key={`${f.id || f.label_en}-${i}`}><strong>{lang === 'hi' ? f.label_hi : f.label_en}</strong><blockquote>“{friendlyEvidence(f.evidence)}”</blockquote></article>)}</div></section>}<article className="explanation-card"><div className="row-between"><h2>{t.explanation}</h2><button className="listen-button" onClick={listen}>{speaking ? t.stop : t.listen}</button></div><p>{lang === 'hi' ? analysis.explanation_hi : analysis.explanation_en}</p></article><button className="recovery-button" onClick={() => setScreen('sent')}>{t.sentMoney}</button><section><h2>{t.next}</h2><div className="action-grid"><a href="tel:1930">{t.call}</a><a href="https://cybercrime.gov.in" target="_blank" rel="noreferrer">{t.cyber}</a><a href="https://scores.sebi.gov.in" target="_blank" rel="noreferrer">{t.sebi}</a></div><h3>{t.steps}</h3><ul className="steps">{(lang === 'hi' ? analysis.next_steps_hi : analysis.next_steps_en).map((s, i) => <li key={i}>✓ {s}</li>)}</ul></section><div className="result-actions"><button className="secondary-button" onClick={() => navigator.share?.({ title: 'Sachet warning', text: `Sachet says: ${verdict}. Pause and verify before paying.` })}>{t.share}</button><button className="pause-link" onClick={() => setScreen('pause')}>◷ {t.pause}</button></div><p className="disclaimer">{analysis.disclaimer} {analysis.verdict === 'no_red_flags_found' && (lang === 'hi' ? 'यह कोई गारंटी नहीं है।' : 'This is not a guarantee.')}</p><button className="secondary-button full" onClick={reset}>{t.another}</button></section>}
    {screen === 'sent' && <section className="content-section"><p className="eyebrow">SACHET</p><h1>{t.sentTitle}</h1><ol className="recovery-list">{t.sentSteps.map((step: string, index: number) => <li key={step}><span>{index + 1}</span><p>{index === 1 ? <a href="tel:1930">{step}</a> : index === 2 ? <>{step.split('cybercrime.gov.in')[0].replace(/[.।]\s*$/, '')}<a href="https://cybercrime.gov.in" target="_blank" rel="noreferrer">cybercrime.gov.in</a></> : step}</p></li>)}</ol><p className="recovery-note">{t.sentNote.split('scores.sebi.gov.in')[0]}<a href="https://scores.sebi.gov.in" target="_blank" rel="noreferrer">scores.sebi.gov.in</a>{t.sentNote.split('scores.sebi.gov.in')[1]}</p><p className="recovery-footer">{t.sentFooter}</p><section className="complaint-form" aria-labelledby="complaint-title"><h2 id="complaint-title">{complaintText.title}</h2><label>{complaintText.date}<input value={complaint.date} onChange={(e) => updateComplaint('date', e.target.value)} type="datetime-local" /></label><label>{complaintText.amount}<input value={complaint.amount} onChange={(e) => updateComplaint('amount', e.target.value)} inputMode="decimal" /></label><label>{complaintText.paid}<select value={complaint.paid} onChange={(e) => updateComplaint('paid', e.target.value)}>{complaintText.options.map((option) => <option key={option}>{option}</option>)}</select></label><label>{complaintText.recipient}<input value={complaint.recipient} onChange={(e) => updateComplaint('recipient', e.target.value)} /></label><label>{complaintText.started}<select value={complaint.started} onChange={(e) => updateComplaint('started', e.target.value)}>{complaintText.origins.map((option) => <option key={option}>{option}</option>)}</select></label><label>{complaintText.transaction}<input value={complaint.transaction} onChange={(e) => updateComplaint('transaction', e.target.value)} /></label><label>{complaintText.happened}<textarea value={complaint.happened} onChange={(e) => updateComplaint('happened', e.target.value)} rows={5} /></label><button className="primary-button" onClick={generateDraft}>{complaintText.generate}</button>{draft && <div className="draft-box"><pre>{draft}</pre><div className="draft-actions"><button className="secondary-button" onClick={copyDraft}>{complaintText.copy}</button><button className="secondary-button" onClick={shareDraft}>{complaintText.share}</button></div><p>{complaintText.note}</p></div>}</section><button className="secondary-button full" onClick={() => setScreen('check')}>{t.sentBack}</button></section>}
    {screen === 'pause' && <section className="content-section"><p className="eyebrow">SACHET</p><h1>{t.pause}</h1><p className="subtitle">{t.pauseIntro}</p><div className="question-list">{t.questions.map((q, i) => <div className="question-row" key={q}><p>{q}</p><div className="answer-toggle"><button className={answers[i] ? 'answer-active answer-yes' : ''} onClick={() => setAnswers((a) => a.map((v, j) => j === i ? true : v))}>{t.yes}</button><button className={!answers[i] ? 'answer-active' : ''} onClick={() => setAnswers((a) => a.map((v, j) => j === i ? false : v))}>{t.no}</button></div></div>)}</div>{answers.some(Boolean) ? <div className="stop-callout" role="alert"><strong>{t.stopPay}</strong></div> : <div className="safe-callout">{t.safe}</div>}<button className="secondary-button full" onClick={reset}>{t.another}</button></section>}
    <footer className="site-footer">Sachet · सचेत <span>For awareness, not advice.</span></footer></main>
}
